sudo: false
os:
  - linux
  - osx

language: node_js
node_js:
  - "6"
  - "7"

script:
  - where npm
  - where node
  - node --version
  - npm --version
  - npm install
  - npm run publish-release-binaries
