environment:
  matrix:
  - nodejs_version: "4"
    platform: x64
  - nodejs_version: "4"
    platform: x86
  - nodejs_version: "5"
    platform: x64
  - nodejs_version: "5"
    platform: x86
  - nodejs_version: "6"
    platform: x64
  - nodejs_version: "6"
    platform: x86
  - nodejs_version: "6.9.1"
    platform: x64
  - nodejs_version: "6.9.1"
    platform: x86
  - nodejs_version: "Stable"
    platform: x64
  - nodejs_version: "Stable"
    platform: x86

install:
  - where npm
  - where node
  - node --version
  - npm --version
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - npm run publish-release-binaries

build: off
