environment:
  matrix:
  - nodejs_version: "4"
    platform: x64
  - nodejs_version: "4"
    platform: x86
  - nodejs_version: "5"
    platform: x64
  - nodejs_version: "5"
    platform: x86
  - nodejs_version: "6"
    platform: x64
  - nodejs_version: "6"
    platform: x86

install:
  - where npm
  - where node
  - echo %APPVEYOR_REPO_NAME%
  - node --version
  - npm --version
  - set PATH=%APPDATA%\npm;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g node-gyp node-pre-gyp node-pre-gyp-github
  - ps: if($env:APPVEYOR_REPO_NAME.Equals('uojs/master')) { node-pre-gyp package; node-pre-gyp-github publish --release }

build: off
